import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextArea;
import javafx.scene.layout.BorderPane;
import javafx.scene.paint.Color;

import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;

public class MenuExample extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("JavaFX Menu Example");

        // Create a menu bar and menus
        MenuBar menuBar = new MenuBar();
        Menu fileMenu = new Menu("File");
        Menu dateMenu = new Menu("Date/Time");
        Menu colorMenu = new Menu("Color");
        Menu exitMenu = new Menu("Exit");

        // Create menu items
        MenuItem printDateTimeItem = new MenuItem("Print Date/Time");
        MenuItem writeToLogFileItem = new MenuItem("Write to Log File");
        MenuItem changeBackgroundColorItem = new MenuItem("Change Background Color");
        MenuItem exitItem = new MenuItem("Exit");

        // Add menu items to menus
        dateMenu.getItems().add(printDateTimeItem);
        fileMenu.getItems().add(writeToLogFileItem);
        colorMenu.getItems().add(changeBackgroundColorItem);
        exitMenu.getItems().add(exitItem);

        // Create a text area to display content
        TextArea textArea = new TextArea();
        textArea.setPrefWidth(400);
        textArea.setPrefHeight(300);

        // Set action handlers for menu items
        printDateTimeItem.setOnAction(event -> {
            LocalDateTime now = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            textArea.appendText(formatter.format(now) + "\n");
        });

        writeToLogFileItem.setOnAction(event -> {
            try {
                FileWriter writer = new FileWriter("log.txt", true);
                writer.write(textArea.getText());
                writer.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        });

        changeBackgroundColorItem.setOnAction(event -> {
            Random random = new Random();
            Color randomColor = Color.color(random.nextDouble(), 1.0, random.nextDouble());
            textArea.setStyle("-fx-control-inner-background: " + toHex(randomColor) + ";");
        });

        exitItem.setOnAction(event -> {
            primaryStage.close();
        });

        // Add menus to the menu bar
        menuBar.getMenus().addAll(fileMenu, dateMenu, colorMenu, exitMenu);

        // Create the layout
        BorderPane layout = new BorderPane();
        layout.setTop(menuBar);
        layout.setCenter(textArea);

        Scene scene = new Scene(layout, 600, 400);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    // Convert Color to HEX for CSS styling
    private String toHex(Color color) {
        int r = (int) (color.getRed() * 255);
        int g = (int) (color.getGreen() * 255);
        int b = (int) (color.getBlue() * 255);
        return String.format("#%02X%02X%02X", r, g, b);
    }
}
